[package]
name = "tc"
version = "0.1.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
edition = "2018"

[dependencies]
tract-core = { path = "../core" }
tclib = { path = "lib" }
# tract-onnx = { path = "../onnx" }
